# This is a basic workflow to help you get started with Actions
name: CI Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
    branches: [ "dev" ]
jobs:    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'dev-stackovergame.com.br'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn  
      
  deploy-hml:
    runs-on: ubuntu-latest
    environment:
      name: hml
      url: 'html-stackovergame.com.br'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn 
  
  build:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    needs: deploy-hml
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      
