# This is a basic workflow to help you get started with Actions
name: CI Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn 
      - run: yarn dev
